# Generated by Django 6.0.1 on 2026-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexalix_app", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags, e.g. Fintech, AI, Automation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Brief description shown on the homepage partner card",
            ),
        ),
    ]
