# Generated by Django 6.0.1 on 2026-03-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexalix_app", "0003_casestudy_tags_partner_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="quote_base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=3500.0,
                help_text="Base starting price used by the Auto Quote Generator.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="quote_delivery_weeks",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Typical delivery timeline in weeks for this service.",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="show_in_quote_generator",
            field=models.BooleanField(
                default=True,
                help_text="Make this service selectable in the Auto Quote Generator.",
            ),
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_reference",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("starter", "Starter / MVP"),
                            ("growth", "Growth"),
                            ("advanced", "Advanced"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="growth",
                        max_length=20,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Timeline"),
                            ("accelerated", "Accelerated Timeline"),
                            ("urgent", "Urgent Timeline"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "support_plan",
                    models.CharField(
                        choices=[
                            ("none", "No Ongoing Support"),
                            ("standard", "Standard Support"),
                            ("premium", "Premium Support"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("project_summary", models.TextField()),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "estimated_subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "addons_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "support_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "estimated_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "estimated_min",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "estimated_max",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("estimated_weeks", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("sent", "Quote Sent"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_addons",
                    models.ManyToManyField(
                        blank=True,
                        related_name="quote_requests",
                        to="nexalix_app.quoteaddon",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nexalix_app.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
