# Generated by Django 6.0.2 on 2026-03-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexalix_app", "0004_quoteaddon_service_quote_base_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewed", "Reviewed"),
                    ("sent", "Quote Sent"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
    ]
