# Generated by Django 6.0.2 on 2026-03-08 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexalix_app", "0005_alter_contactmessage_is_read_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardSavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("period_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "activity_filter",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("contact", "Contacts"),
                            ("quote", "Quotes"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
                (
                    "role_view",
                    models.CharField(
                        choices=[
                            ("all", "All Views"),
                            ("sales", "Sales"),
                            ("ops", "Ops"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
                (
                    "search_query",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Saved Filter",
                "verbose_name_plural": "Dashboard Saved Filters",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
