# Generated by Django 6.0.2 on 2026-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexalix_app", "0006_dashboardsavedfilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("project_needs", models.TextField()),
                (
                    "interested_services",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated service names.",
                        max_length=250,
                    ),
                ),
                ("assistant_summary", models.TextField(blank=True)),
                ("source_page", models.CharField(blank=True, max_length=255)),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "escalation_channel",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("whatsapp", "WhatsApp"),
                            ("contact", "Contact Form"),
                            ("email", "Email"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_escalated", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chatbot Lead",
                "verbose_name_plural": "Chatbot Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
