# Generated by Django 6.0.2 on 2026-03-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexalix_app", "0007_chatbotlead"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdatesSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("source", models.CharField(default="footer", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Updates Subscriber",
                "verbose_name_plural": "Updates Subscribers",
                "ordering": ["-created_at"],
            },
        ),
    ]
