# Generated by Django 6.0.1 on 2026-03-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexalix_app', '0008_add_updates_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-is_featured', 'order', '-created_at'], 'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='engagement_type',
            field=models.CharField(blank=True, help_text='Optional delivery tier or engagement type, e.g. MVP Sprint, Advisory Engagement', max_length=120),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='proof_type',
            field=models.CharField(choices=[('case_study', 'Case Study'), ('sample_implementation', 'Sample Implementation'), ('internal_prototype', 'Internal Prototype'), ('solution_example', 'Solution Example')], default='case_study', max_length=32),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated technologies used in this delivery story', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
