# Generated by Django 6.0.1 on 2026-03-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexalix_app', '0009_alter_casestudy_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='schema_markup_json',
            field=models.TextField(blank=True, help_text='Optional JSON-LD override or supplemental schema.'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='social_share_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='service',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_items',
            field=models.TextField(blank=True, help_text='One FAQ per line using the format: Question | Answer'),
        ),
        migrations.AddField(
            model_name='service',
            name='schema_markup_json',
            field=models.TextField(blank=True, help_text='Optional JSON-LD override or supplemental schema.'),
        ),
        migrations.AddField(
            model_name='service',
            name='social_share_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
    ]
