# Generated by Django 6.0.2 on 2026-03-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexalix_app', '0010_casestudy_canonical_url_casestudy_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSolutionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(default='fas fa-layer-group', max_length=100)),
                ('value_statement', models.TextField(help_text='Short outcome-led statement shown on solution cards.')),
                ('business_problem', models.TextField()),
                ('who_for', models.TextField(help_text='Describe who this solution cluster is best suited for.')),
                ('deliverables', models.TextField(help_text='One deliverable per line')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords used to match related services and proof.')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('primary_cta_text', models.CharField(default='Get Proposal', max_length=60)),
                ('secondary_cta_text', models.CharField(default='Book Consultation', max_length=60)),
            ],
            options={
                'verbose_name': 'Service Solution Cluster',
                'verbose_name_plural': 'Service Solution Clusters',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='processstep',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class, e.g. fas fa-rocket', max_length=100),
        ),
        migrations.AddField(
            model_name='processstep',
            name='outputs',
            field=models.TextField(blank=True, help_text='One expected output per line'),
        ),
        migrations.AddField(
            model_name='service',
            name='solution_cluster',
            field=models.ForeignKey(blank=True, help_text='Optional manual mapping to a solution cluster used across the public site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='nexalix_app.servicesolutioncluster'),
        ),
        migrations.CreateModel(
            name='SolutionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nav_title', models.CharField(max_length=160)),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.TextField()),
                ('problems', models.TextField(help_text='One problem statement per line')),
                ('deliverables', models.TextField(help_text='One deliverable per line')),
                ('technologies', models.TextField(help_text='One technology per line')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords used to match services and case studies.')),
                ('faq_items', models.TextField(blank=True, help_text='One FAQ per line using the format: Question | Answer')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('social_share_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('schema_markup_json', models.TextField(blank=True, help_text='Optional JSON-LD override or supplemental schema.')),
                ('solution_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_pages', to='nexalix_app.servicesolutioncluster')),
            ],
            options={
                'verbose_name': 'Solution Page',
                'verbose_name_plural': 'Solution Pages',
                'ordering': ['order', 'nav_title'],
            },
        ),
    ]
