# Generated by Django 6.0.2 on 2026-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexalix_app', '0012_seed_solution_pages_and_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='industries/'),
        ),
    ]
